### ISSUE TITLE
post 发送json时，产生415错误

### ISSUE THREAD

**Issue by bj379724952** [tommut/HttpRequester#32]
在火狐升级到51.0.1时，post 发送json时，产生415参数错误，退回到50.0.2时，正常

**Comment by yellowanwu** [comment]
MoTo  February 7, 2017 · 

It was working fine till I updated to firefox 51, from then Content-Type header value is duplicated, for example lets assume Content-Type is supposed to be "application/json" but when request is send by HttpRequester the Content-Type that I get on server side is "application/josn; application/josn". so that content type checks on server side may fail.

**Comment by tommut** [comment]
Should be now fixed with v2.2.  Thanks.
